services:
  grpc-server:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    volumes:
      - .:/app
      - /app/.venv
      - hf_cache:/root/.cache/huggingface
    init: true
    ports:
      - "${GRPC_PORT}:50051"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - qdrant
    command: ["python", "src/app/main.py"]
    networks:
      - local-network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "${QDRANT_DB_PORT}:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage:z
    restart: always
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - local-network

volumes:
  hf_cache:
  qdrant_data:

networks:
  local-network:
    driver: bridge
