services:
  grpc-server:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    volumes:
      - .:/app
      - /app/.venv
    working_dir: /app
    ports:
      - "50051:50051"
    environment:
      - PYTHONPATH=/app/src:/app/src/genpb
      - PYTHONDONTWRITEBYTECODE=1
    env_file:
      - .env
    command: >
      uv run watchmedo auto-restart 
      --recursive 
      --pattern="*.py" 
      --directory="./src" 
      python src/app/main.py
    depends_on:
      - langgraph-server
    networks:
      - local-network

  langgraph-server:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    ports:
      - "2024:2024"
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - PYTHONPATH=/app/src
      - PYTHONDONTWRITEBYTECODE=1
    env_file:
      - .env
    command: uv run langgraph dev --host 0.0.0.0 --port 2024
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
