# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat/v1/message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chat/v1/message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63hat/v1/message.proto\x12\x07\x63hat.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"X\n\x12\x43hatMessageRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05\x61gent\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"*\n\tErrorInfo\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xc5\x01\n\x11\x43hatChunkResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12 \n\x04type\x18\x02 \x01(\x0e\x32\x12.chat.v1.ChunkType\x12\x0c\n\x04node\x18\x03 \x01(\t\x12&\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x12.chat.v1.ErrorInfoH\x00\x88\x01\x01\x12\x10\n\x08is_final\x18\x05 \x01(\x08\x12-\n\ttimestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x08\n\x06_error*O\n\tChunkType\x12\x1a\n\x16\x43HUNK_TYPE_UNSPECIFIED\x10\x00\x12\x0e\n\nTYPE_TOKEN\x10\x01\x12\x16\n\x12TYPE_NODE_COMPLETE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat.v1.message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHUNKTYPE']._serialized_start=401
  _globals['_CHUNKTYPE']._serialized_end=480
  _globals['_CHATMESSAGEREQUEST']._serialized_start=67
  _globals['_CHATMESSAGEREQUEST']._serialized_end=155
  _globals['_ERRORINFO']._serialized_start=157
  _globals['_ERRORINFO']._serialized_end=199
  _globals['_CHATCHUNKRESPONSE']._serialized_start=202
  _globals['_CHATCHUNKRESPONSE']._serialized_end=399
# @@protoc_insertion_point(module_scope)
